name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.3

      - name: Install tools
        run: python -m pip install --upgrade pip pytest
      
      - name: Install requests
        run: pip install requests
      
      - name: Install pandas
        run: pip install pandas

      - name: Test with unittest
        run: python3 -m unittest weadar_test.py
 
      - name: Check code coverage
        run: |
            python3 coverage run -m unittest weadar_test.py
            python3 coverage report
            python3 coverage html

      - name: Archive code coverage HTML report
        uses: actions/upload-artifact@v2
        with:
            name: code-coverage-report
            path: htmlcov